### PR TITLE
Pulling in the latest drops7

### PR DESCRIPTION
**Pull request by pirog**
PR to merge in the latest upstream changes from drops7 aka updating core to 7.41

### CODE REVIEW

**Comment by kreynen** [comment]
This is just the updates to Drupal core.  Are you planning another PR with the updates to CiviCRM and contrib?

**Comment by pirog** [comment]
Yes. this is just the updates to drupal core. 

I am potentially going to submit another PR with support for pantheon-on-kalabox2 depending on how difficult it is to do that. 

Either way i figured an update to core seemed worth doing since its easy and we are behind a big here.

**Comment by pirog** [comment]
https://github.com/kalabox/kalabox/issues/658 for reference

**Comment by pirog** [comment]
@kreynen i see that you have wisely not allowed issues here so i'm going to just ask in this PR, breaking all normal github collab conventions!

I've put together a more "portable" version of the pantheon section in civicrm.settings.php over here https://github.com/kalabox/kalabox/issues/658#issuecomment-153466758

This should work regardless of the pantheon instance/environment you are on including locally on kalabox2. That said i am not exactly sure the best way to get this into the install profile workflow. If you could point me in the right direction there i'd gladly submit a PR.

If you are not interested in any of this at all i can post a wiki page on the kalabox pantheon integration page detailing how to get civicrm going locally.

**Comment by pirog** [comment]
NM, found it and opened https://github.com/kreynen/civicrm-starterkit-drops-7/pull/2

**Comment by herbdool** [comment]
@pirog I've taken on the thankless task and going to start nudging this forward slowly until it's got security updates and LTS. I'll get to this soon (and also get it up to 7.50+).

**Comment by kreynen** [comment]
@herbdool I thank you!

**Comment by herbdool** [comment]
I'm going to close this PR since I've pulled in drops-7 for 7.51.

**Pull request closed without merging**
