### PR TITLE
Make pantheon civicrm settings more portable, kalabox2 support

### PR DESCRIPTION
**Pull request by pirog**
@kreynen here is a small PR that refactors our settings template to make the settings a little more portable so they work out of the box on kalabox2

### CODE REVIEW

**Comment by soniktrooth** [comment]
+1

**Comment by labboy0276** [comment]
+1

**Comment by gremy** [comment]
+1

**Comment by kreynen** [comment]
I'm glad this is finally getting some attention, but I'm not sure what these +1s actually mean.  

Did anyone actually test this?  Do these settings work with the current CiviCRM releases?

The community media groups that funded the development of the initial CiviCRM Starter Kit distribution asked Kalamuna for help with this back in 2014 http://cmdrupal.org/content/community-media-drupal-austin-may-31-june-1, but it didn't go anywhere.  

Should I just add my +1 to the list or are these +1s your way of volunteering time to help test these updates?

I wrote a bit about how to update CiviCRM in individual Pantheon sites in https://www.drupal.org/node/1694794, but I should probably add more info to GitHub.  PR that only fix issues for Pantheon on GitHub aren't really that useful since we use Drupal.org to build this distribution from the starter kit specific builds that the CiviCRM creates for each of these release.  So we start with http://cgit.drupalcode.org/civicrm_starterkit/tree/drupal-org.make#n10 and apply patches to build the distribution using drush make.  

Changes required to get CiviCRM to run on Pantheon are applied as patches in http://cgit.drupalcode.org/civicrm_starterkit/tree/drupal-org.make#n15.  Updates need to be made in issues like the https://www.drupal.org/node/1978838 so the changes can be reapplied to latest version of CiviCRM.

Unfortunately there is a lot of more work needed to update the patches to the current version of CiviCRM... work I really don't have time (or interest) to do alone.  If there is actually a community forming around getting and keeping CiviCRM working well on Pantheon, I'm happy to help facilitate... but let's move the discussions back to https://www.drupal.org/project/civicrm_starterkit

**Comment by pirog** [comment]
These settings are tested just within the context of this repo on pantheon and on kalabox2 locally. The changes made here are pantheon specific so they would only break new civi versions if newer versions of civi made breaking changes to their own settings. 

Generally a +1 is just a thumbs up for a merge. I dig that you tried to turn that into a way of signaling interest in volunteering though. 

Our primary interest here is to help get people using Kalabox2 with pantheon into a spot where they can easily pull down a civi site and have it work locally without having to change their settings file. I dont think we have a ton of time or energy to update the entire starterkit. 

I'd be more than happy to get this particular patch, and core updates, into the d.o project starterkit in the way you describe but i'm less keen on experimenting with the latest version of civicrm and getting that to work since that could potentially be a huge black hole of lost time.

**Review by herbdool — APPROVED** [review]

**Pull request merged**
